config/routes.rb
Rails.application.routes.draw do
  root 'homepage#index'
  post 'homepage/info', to: 'homepage#info', as: 'homepage_info'

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homepage_controller.rb
# frozen_string_literal: true

# HomepageController
class HomepageController < ApplicationController
  before_action :set_variables, only: %i[index]

  def index
    @errors = params[:errors]
  end

  def info
    @params = params
    params['income'] = params['income'].reject(&:empty?)

    if must_return
      redirect_to root_path(errors: 'Preencha todos os campos')
      return
    end

    system("python3 app/jobs/esi/esi.py '#{info_params}'")

    sleep(5)
  end

  private

  def set_variables
    # Mais de 2 a 3 SM:
    @initial_group = %w[
      350600305000103 350600305000191 350600305000194 350600305000197 350600305000301
      350600305000449 350600305000505
    ]

    # Mais de 3 a 5 SM:
    @second_group = %w[
      350600305000102 350600305000106 350600305000108 350600305000025 350600305000059 350600305000061 350600305000099
      350600305000144 350600305000148 350600305000149 350600305000153 350600305000193 350600305000250 350600305000252
      350600305000259 350600305000260 350600305000261 350600305000299 350600305000300 350600305000343 350600305000381
      350600305000481 350600305000482 350600305000490 350600305000497
    ]
    # Mais de 5 a 10 SM:
    @third_group = %w[
      350600305000104 350600305000105 350600305000107 350600305000537 350600305000538 350600305000151 350600305000154
      350600305000155 350600305000156 350600305000157 350600305000195 350600305000196 350600305000198 350600305000199
      350600305000200 350600305000201 350600305000202 350600305000203 350600305000204 350600305000256 350600305000257
      350600305000258 350600305000297 350600305000298 350600305000344 350600305000377 350600305000410 350600305000411
      350600305000480 350600305000487 350600305000506 350600305000509
    ]

    # Mais de 10 SM:
    @fourth_group = %w[
      350600305000450
    ]
  end

  def must_return
    params.values_at('type', 'income', 'trading', 'another_markets', 'busy_streets').any?(&:blank?)
  end

  def info_params
    params.except(:authenticity_token, :commit, :controller, :action).to_json
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homepage/get_info.html.erb
<%= link_to "Voltar", root_path, class: "botao-voltar" %>

<%# talvez colocar a div content aqui %>
<div>
    <h1>Bem-vindo ao Sistema de Localização para Novos Supermercados em Bauru!</h1>
    <p>
        Nosso objetivo é ajudar novos empreendimentos a encontrar o ponto ideal para atender ao público de Bauru com eficiência e conveniência. Este sistema foi desenvolvido para auxiliar na escolha de locais estratégicos para a abertura de uma nova loja de supermercado, voltada para atender consumidores com renda familiar per capita de pelo menos 2 salários mínimos.
    </p>
    <p>
        Através de uma análise detalhada e visualização em mapa, identificamos as áreas que melhor atendem aos critérios de acessibilidade, concorrência e presença de negócios complementares. Assim, ajudamos a maximizar as chances de sucesso do empreendimento.
    </p>
    <p>Após explorar o mapa, preencha o formulário para receber informações detalhadas sobre a localização ideal para o seu supermercado.</p>
</div>

<%= render 'layouts/relative_map'%>

app/views/homepage/index.html.erb
<div class="container">
    <div class="content">
        <h1>Bem-vindo ao Sistema de Localização para Novos Supermercados em Bauru!</h1>
        <p>
            Nosso objetivo é ajudar novos empreendimentos a encontrar o ponto ideal para atender ao público de Bauru com eficiência e conveniência. Este sistema foi desenvolvido para auxiliar na escolha de locais estratégicos para a abertura de uma nova loja de supermercado, <b>voltado para a área em Bauru com renda predominante maior que 2 salários mínimos</b>.
        </p>
        <p>
            Através de uma análise detalhada e visualização em mapa, que exibe os valores de salário mínimos por região, identificamos as áreas que melhor atendem aos critérios de acessibilidade, concorrência e presença de negócios complementares. Assim, ajudamos a maximizar as chances de sucesso do empreendimento.
        </p>
        <p>Após explorar o mapa, preencha o formulário abaixo para receber informações detalhadas sobre a localização ideal para o seu supermercado.</p>
    </div>

    <div class="form-container">
        <%if @errors%>
            <div class="error-message">
                <span class="icon">⚠️</span>
                <div class="text">
                    <%=@errors.to_s%>
                </div>
            </div>
        <%end%>

        <%= form_with url: homepage_info_path, method: :post, local: true do |f| %>
            <div class="form-group">
                <%= f.label :type, "Tipo do imóvel:" %><br>
                <%= f.check_box :type, { multiple: true }, 'compra', nil %> Compra
                <%= f.check_box :type, { multiple: true }, 'aluguel', nil %> Aluguel
            </div>
            <div class="form-group">
                <%= f.label :income, "Selecione os rendimentos dos domicílios" %>
                <%= f.select :income, options_for_select([
                ['Domicílios com Rendimento > 2 a 3 salários mínimos', @initial_group],
                ['Domicílios com Rendimento > 3 a 5 salários mínimos', @second_group],
                ['Domicílios com Rendimento > 5 a 10 salários mínimos', @third_group],
                ['Domicílios com Rendimento > 10 salários mínimos', @fourth_group],
                ]), {}, { multiple: true, class: "form-control" } %>
            </div>

            <div class="form-group">
                <%= f.label :another_markets, "Perto de outros mercados?" %><br>
                <%= f.radio_button :another_markets, 1 %> Sim
                <%= f.radio_button :another_markets, 0 %> Não
            </div>

            <div class="form-group">
                <%= f.label :trading, "Perto dos Comercios?" %><br>
                <%= f.radio_button :trading, 1 %> Sim
                <%= f.radio_button :trading, 0 %> Não
            </div>

            <div class="form-group">
                <%= f.label :busy_streets, "Perto de Vias Movimentadas?" %><br>
                <%= f.radio_button :busy_streets, 1 %> Sim
                <%= f.radio_button :busy_streets, 0 %> Não
            </div>

            <div class="form-group">
                <%= f.submit "Enviar", class: "btn btn-primary" %>
            </div>
        <% end %>
    </div>
</div>

<%= render 'layouts/map'%>

app/views/homepage/info.html.erb
<div class="container">
    <div class = "content">
        <h2>Seus resultados</h2>
        <p>
            O mapa foi configurado conforme as preferências do usuário, destacando apenas as regiões que atendem aos critérios de rendimento definidos. A visualização foca em setores de Bauru com imóveis em áreas de renda predominante superior a 2 salários mínimos, facilitando uma análise direcionada da distribuição de imóveis conforme o perfil de demanda.</p>
        </p>

        <p><b>Caso se interesse por uma região, clique nela para acessar o link do imóvel.</b></p>
    </div>

    <div class = "content">
        <h2>Suas escolhas: </h2>
        <ul>
            <li><b>Tipo de imóvel:</b> <%= @params['type'].join(", ") %></li>
            <li><b>Perto de outros mercados:</b> <%= @params['another_markets'] == '1' ? "Sim" : "Não" %></li>
            <li><b>Perto dos Comercios:</b> <%= @params['trading'] == '1' ? "Sim" : "Não" %></li>
            <li><b>Perto de Vias Movimentadas:</b> <%= @params['busy_streets'] == '1' ? "Sim" : "Não" %></li>
        </ul>
        <div>
            <%= link_to "Faça novamente", root_path, class: "botao-voltar" %>
        </div>
    </div>
</div>
<%= render 'layouts/relative_map'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Localização Ideal para Supermercado em Bauru</title>

    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>